import matplotlib.pyplot as plt
import pandas as pd
d=pd.read_csv('diabetes.csv')
# print("Top 5 records\n",d.head(5))
# print("Bottom 5 records\n",d.tail(5))
# plt.scatter(d['Age'], d['BloodPressure'])
# plt.xlabel('Age')
# plt.title('Blood pressure \n Age vs Blood Pressure')
# plt.show()
# plt.plot(d['Age'], d['BMI'])
# plt.xlabel('Age')
# plt.ylabel('BMI')
# plt.title('Age vs BMI')
# plt.show()
fig, axes = plt.subplots(2, 2, figsize=(10, 10))
axes[0, 0].scatter(d['Age'], d['BMI'])
axes[0, 0].set_xlabel('Age')
axes[0, 0].set_ylabel('BMI')
axes[0, 0].set_title('Age vs BMI')
axes[0, 1].scatter(d['Age'], d['BloodPressure'])
axes[0, 1].set_xlabel('Age')
axes[0, 1].set_title('Blood pressure\nAge vs Blood Pressure')
axes[1, 0].scatter(d['Age'], d['Pregnancies'])
axes[1, 0].set_xlabel('Age')
axes[1, 0].set_ylabel('Pregnancies')
axes[1, 0].set_title('Age vs Pregnancies')
axes[1, 1].scatter(d['Age'], d['Glucose'])
axes[1, 1].set_xlabel('Age')
axes[1, 1].set_ylabel('Glucose')
axes[1, 1].set_title('Age vs Glucose')
plt.tight_layout()
plt.show()